### ISSUE TITLE
check for feasibility to automatically prefill the annotation UI

### ISSUE THREAD

**Issue by ThijsRoumen** [janetzki/Mechanism-Browser#26]
would be cool to just use a URL to a mechanism, crawl relevant information and prefill this into the annotation UI. It would for example take the images from IMG tags and displays the largest one by default. Also the largest amount of uninterrupted text is probably the description, a link to an STL file is probably the 3D model etc. 

All the user would need to do is specify the axes of rotation/translation and check the automatic suggestions (overrule where needed). I would be curious to see how far this gets us

**Comment by janetzki** [comment]
Conclusion: It is more efficient to implement custom crawlers for online mechanism databases as they all have a different structure and a crawler can generate articles faster. PR #68 will introduce such a crawler.
